services:
  mysql:
    image: mysql:8.0
    container_name: mysql-savvylingua
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Empty password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Explicitly allow it
      MYSQL_DATABASE: savvylingua
    ports:
      - "3307:3306"
    networks:
      - savvy_network
    volumes:
      - mysql_data:/var/lib/mysql
