version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-savvy
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: savvydb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
