version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-savvylingua
    environment:
      MYSQL_DATABASE: savvylingua
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - savvy_network
    volumes:
      - ./db_data:/var/lib/mysql # bind mount: this will persist even with down -v
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: flask-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - savvy_network
    volumes:
      - .:/app
      - ./uploads:/app/uploads  # sync with uploads/ folder on disk

networks:
  savvy_network:
    driver: bridge
