version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-savvylingua
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: savvylingua
    ports:
      - "3307:3306"
    networks:
      - savvy_network
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  savvy_network:
    driver: bridge
